cloud-drive:
  # 数据库
  db:
    host: mysql
    pw: MnMysql123*
  # Redis
  redis:
    host: redis
    pw: redis123
  # 文件存储目录
  disk:
    storage-path: /clouddrive/cloudfile
    file-dir: file
    temp-dir: temp
  # 用户令牌
  jwt:
    # 7200000 2小时
    user-ttl: 7200000
  # 分享
  share:
    link:
      protocol: https
      host: cloud.softspark.cn
      port: 443
      path: /#/sharelink

# ElasticSearch 文件搜索
elastic-search:
  host: elastic
  port: 9200
  scheme: http
  username: elastic
  password: mnelastic123

# kkFileView 文件预览
kkfileview:
  origin:
    protocol: http # HTTP 协议
    host: cloud-server  # 容器
    port: 8080       # 端口号
    path: /user/view/file  # 路径
  preview:
    protocol: http
    host: fileview.softspark.cn  # 容器
    port: 80  # 8012 目前是nginx转发 80  443
    path: /onlinePreview
