server:
  port: 8080

spring:
  application:
    name: cloud-server
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_drive
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.netdisk.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


cloud-drive:
  disk:
    storage-path: E:\\cloudfile
    temp-dir: temp
